#!/bin/sh
# 1) Copies index.html into public/ (the folder you upload to the web host).
# 2) Embeds index.html into the edge function as page.ts.
# Run after editing index.html.
set -e
cd "$(dirname "$0")"
mkdir -p public
cp index.html public/index.html
node -e '
const fs = require("fs");
const html = fs.readFileSync("index.html", "utf8");
if (html.includes("`") || html.includes("${")) { console.error("index.html must not contain backticks or ${"); process.exit(1); }
const out = "supabase/functions/expense-tracker/page.ts";
fs.writeFileSync(out, "// Generated by build.sh from index.html. Do not edit by hand.\nexport const HTML: string = String.raw`" + html + "`;\n");
console.log("updated public/index.html and", out);
'
